/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "eu-central-1",
  aws_cognito_identity_pool_id:
    "eu-central-1:d5434e77-f7f9-4408-81d8-03e6801b2e21",
  aws_cognito_region: "eu-central-1",
  aws_user_pools_id: "eu-central-1_cZQiOpjTI",
  aws_user_pools_web_client_id: "7n0p3lfk6m3dft07vpccdhpnli",
  oauth: {},
  aws_cognito_username_attributes: ["EMAIL"],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: [],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [
      "REQUIRES_LOWERCASE",
      "REQUIRES_NUMBERS",
      "REQUIRES_SYMBOLS",
      "REQUIRES_UPPERCASE",
    ],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
  aws_appsync_graphqlEndpoint:
    "https://smpcihzn7rdqrlsynamu6y37ty.appsync-api.eu-central-1.amazonaws.com/graphql",
  aws_appsync_region: "eu-central-1",
  aws_appsync_authenticationType: "API_KEY",
  aws_appsync_apiKey: "da2-x4i4astlefdchdr5fm7glscoxm",
  aws_appsync_dangerously_connect_to_http_endpoint_for_testing: true,
  aws_user_files_s3_bucket: "kiekkoprojekti-storage-b2d3a62f193452-staging",
  aws_user_files_s3_bucket_region: "eu-central-1",
};

export default awsmobile;
